package com.example.limeapp.model

data class Channel(
    val address: String,
    val aspectRatio: String,
    val aspect_ratio: String,
    val categories: List<Int>,
    val cdn: String,
    val current: Current,
    val day_archive: Int,
    val epg_id: Int,
    val external_player_code: String,
    val fav: Boolean,
    val foreign_player: ForeignPlayer,
    val foreign_player_key: Boolean,
    val genre: List<Any>,
    val hasEpg: Boolean,
    val href: String,
    val id: Int,
    val image: String,
    val is_foreign: Boolean,
    val name_en: String,
    val name_ru: String,
    val number: Int,
    val pack: List<Any>,
    val promo: Boolean,
    val `public`: Int,
    val quality: List<Int>,
    val region_code: Int,
    val sort: Int,
    val tz: Int,
    val url: String,
    val url_archive: String,
    val url_sound: String,
    val use_external_player: Int,
    val with_archive: Boolean
)